# Generated by Django 5.1.3 on 2024-11-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(upload_to='home_banners/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WEIGHT_LOSS', 'Weight Loss'), ('STRENGTH', 'Strength Training'), ('YOGA', 'Yoga'), ('CARDIO', 'Cardio')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='home_programs/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
