# Generated by Django 5.1.3 on 2024-12-01 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_homebanner_image_remove_homeprogram_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week', models.CharField(choices=[('Week 1', 'Assessment Week'), ('Week 2', 'Main Part'), ('Week 3', 'Deload Week'), ('Week 4', 'Brutal Week'), ('Week 5', 'Stretching')], max_length=20)),
                ('category', models.CharField(choices=[('Abs & Core', 'Abs & Core'), ('Upper Body', 'Upper Body'), ('Lower Body', 'Lower Body'), ('Cardio', 'Cardio')], max_length=20)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('calories_burned', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workout')),
            ],
            options={
                'unique_together': {('user', 'workout')},
            },
        ),
    ]
