# Generated by Django 5.1.3 on 2024-12-04 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_workoutday_workoutprogram_workoutexercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='bodytype',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='api.bodytypeprofile'),
            preserve_default=False,
        ),
    ]
