# Generated by Django 5.1.3 on 2024-12-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workoutprogram_bodytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='week_no',
            field=models.IntegerField(default=1),
        ),
    ]
