# Generated by Django 5.1.3 on 2024-12-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_userexerciseprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='default_set',
            field=models.IntegerField(default=1),
        ),
    ]
