# Generated by Django 5.1.3 on 2024-12-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_workoutexercise_default_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='calories_per_minute',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userexerciseprogress',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
