# Generated by Django 5.1.3 on 2024-12-07 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_foodcategory_food_userfoodlog_favoritefoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='foodcategory',
            name='body_type',
        ),
        migrations.AddField(
            model_name='food',
            name='bodytype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.bodytypeprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodcategory',
            name='bodytype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.bodytypeprofile'),
            preserve_default=False,
        ),
    ]
