# Generated by Django 5.1.3 on 2024-12-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_food_category_remove_foodcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodlog',
            name='quantity',
        ),
        migrations.AddField(
            model_name='userfoodlog',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
