# Generated by Django 5.1.3 on 2024-12-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexerciseprogress',
            name='progress_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userexerciseprogress',
            name='total_workout_time',
            field=models.IntegerField(default=0),
        ),
    ]
