# Generated by Django 5.1.3 on 2025-01-02 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_workoutday_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
